@host =  http://127.0.0.1:3000/users

@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTMxYzI1NGM1Yjg0YzQ1MjRkMjQ4YjQiLCJpYXQiOjE2MzA2NTI4MTUsImV4cCI6MTYzMDcxNzYxNX0.03e9wnRcjD9eXLmNoDect7v_jr1LluurGVHYTa_YvPU

### register
POST {{host}}/register
Content-Type: application/json

{
  "name" : "newName",
  "email": "newName@gmail.com",
  "password": "aA1!aa"
}


### login
POST {{host}}/login
Content-Type: application/json

{
  "email": "passwordRaj@gmail.com",
  "password": "aA1!aa"
}


### user details
GET {{host}}/me
Authorization: {{token}}


### logout
POST {{host}}/logout
Authorization: {{token}}
